version: '3'
services:
    redis:
      image: redis:4-alpine
      ports:
        - 6379:6379
    worker:
      build:
        context: .
        dockerfile: worker.Dockerfile
      depends_on:
        - redis